Develop
jonathanParamo/calculadora pull request #2
Opened 2022-01-19 01:13 UTC by jonathanParamo

2022-01-20 02:41 UTC, Pethofreed requested changes
Los diseños quedaron muy buenos, bonitos efectos, muy presentable la calculadora. Hay que resolver los cambios requeridos. ¡Bien hecho!

2022-01-20 02:41 UTC, Pethofreed commented on calculadora.js
> +function suma(){
No es necesario dejar espacio entre una funcion y otra, pero para mantener la consistencia, deberia dejar un espacio ahí después de la linea 14, porque las demás funciones si están separadas por un espacio.

2022-01-20 02:41 UTC, Pethofreed commented on calculadora.js
> +  if(num && num1 && suma){
¿De dónde sale ese "suma" de la condición? ¿Cúal es el propósito de esa condición, entiendo el (num && num1) pero el "suma" no.

2022-01-20 02:41 UTC, Pethofreed commented on calculadora.js
> +  }
Esta linea tiene mala identación.

2022-01-20 02:41 UTC, Pethofreed commented on calculadora.js
> +  if(num && num1 && resta){
No entiendo el "resta" de la condición, tampoco veo donde se crea o de donde sale. No entiendo porqué está en la condición.

2022-01-20 02:41 UTC, Pethofreed commented on calculadora.js
> +  if(num && num1 && multiplicacion){
Igual que antes, no comprendo la existencia de ese "multiplicacion" en la condición if...tampoco veo de donde sale o se crea... ¿no tira error?

2022-01-20 02:41 UTC, Pethofreed commented on calculadora.js
> +  if(num && num1 && division){
Igual que los 3 anteriores, no veo de donde sale la "division" de la condición.

2022-01-20 02:41 UTC, Pethofreed commented on index.html
> +    <div class="diseño_visual_calculadora">
Error fatal, en los nombres de clases o variables y en general en cualquier lenguaje de programación existente, no se usa la letra "ñ" en ningun lado, solamente dentro de etiquetas html, que sea texto para mostrar, como parrafos, span, inputs, pero no en codigo JS ni nombres de clases ni id. Es mejor usar otra palabra o poner "disenio", tampoco se usan tildes, signos de puntuacion, interrogación, etc.

2022-01-20 02:41 UTC, Pethofreed commented on styles.css
> +.diseño_visual_calculadora {
Para todo el documento CSS, tampoco se usa la "ñ" o signos de "?" o tildes, etc. Debe corregirse en el html y css.

2022-01-20 17:51 UTC, jonathanParamo commented on calculadora.js
> +  if(num && num1 && resta){
en realidad pense que debia estar la condicion.

2022-01-20 18:11 UTC, jonathanParamo commented on styles.css
> +.diseño_visual_calculadora {
acabo de hacer los cambios correspondientes esta listo para una nueva revision

2022-01-20 18:40 UTC, Pethofreed requested changes
No tengo comentarios sobre html o css, los cambios en el JS quedaron bien, pero creo que no me entendió algo sobre las 4 condiciones if. No era eliminar la condición, era quitar solamente la última parte de la condición, y dejar en las 4 funciones lo mismo.

if (num && num1) y quitar (suma, resta, ta,ta,ta....)

2022-01-20 19:22 UTC, jonathanParamo commented
pense que no requeria el condicional, pero al hacer una prueba estaba el nan, al no tener uno o los dos valores en el input, ya se soluciono.

2022-01-21 00:46 UTC, Pethofreed approved these changes

2022-01-22 00:46 UTC, Pethofreed requested changes

2022-01-22 00:46 UTC, Pethofreed commented on index.html
> +        <button onclick="division()" >dividi</button>
En esta linea dice "dividi"

2022-01-22 00:46 UTC, Pethofreed commented on index.html
> +        <button onclick="division()" >dividi</button>
Por lo regular, la primera letra de una palabra en un botón empieza con Mayúscula. Es una sugerencia, no requiere que haga el cambio, pero si tenerlo en cuenta.

2022-01-22 00:46 UTC, Pethofreed commented on calculadora.js
> +  num = document.getElementById("num_dos").value = "";
estas 3 lineas funcionan bien, pero para refactorizar el código, puede (si quiere) eliminar la llamada a la función recibir_numeros y eliminar el num = de las lineas 54 - 55

quedando solo esto:

`function borrar() {
  document.getElementById("num_uno").value = "";
  document.getElementById("num_dos").value = "";
}`

y para que también le limpie la caja de resultado, puede hacer ahí abajo dentro de la misma función

  `const imprimir =` <p> Resultado: 0 </p> `
  resultado.innerHTML = imprimir;`

2022-01-23 15:04 UTC, Pethofreed approved these changes
¡Listo! Ya puede hacer el merge.

2022-01-23 23:20 UTC, merged